### ISSUE TITLE
Thiết kế và triển khai mô hình cơ sở dữ liệu

### ISSUE THREAD

**Issue by vanthaita** [TDevUIT/Kapi#7]
## Summary

Thiết kế và triển khai mô hình cơ sở dữ liệu cho ứng dụng 'Kapi', bao gồm cơ sở dữ liệu quan hệ trên Postgres và lưu trữ video trên Cloudinary/Firebase.

## Scope

Phần này liên quan đến backend của ứng dụng.

- Backend

## Detail

Mô hình cơ sở dữ liệu cần được thiết kế để lưu trữ thông tin về người dùng, khóa học, flashcards, nội dung ngữ pháp và URL của video. Các bảng chính bao gồm:

- **Users**: Lưu thông tin người dùng
- **Courses**: Lưu thông tin khóa học 
- **Flashcards**: Lưu thông tin về các flashcards 
- **Grammar Structures**: Lưu trữ các cấu trúc ngữ pháp 
- **Videos**: Lưu trữ URL video từ Cloudinary 
- More...
Thiết lập migrations ban đầu để tạo các bảng cần thiết và tích hợp cloud storage (Firebase/Cloudinary) để lưu trữ URL của video.

## Further notes

Cần đảm bảo mô hình cơ sở dữ liệu dễ mở rộng và có thể thay đổi khi bổ sung thêm tính năng sau này.

## Checklist

- [ ] Thiết kế schema cho Postgres.
- [ ] Tạo các bảng và chạy migrations.
- [ ] Tích hợp Firebase/Cloudinary để lưu trữ URL video.
- [ ] Kiểm tra mối quan hệ giữa các bảng (users, courses, flashcards, videos).
- [ ] Đảm bảo tính năng lưu trữ và truy xuất video hoạt động ổn định.

**Comment by pinpolhoxx** [comment]
try this
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Archive codepass: changeme

you may need to install the c compiler
